universe = vanilla
notification = Never
request_memory = 32GB
request_disk = 32GB
request_cpus = 16
getenv = True
accounting_group = ligo.prod.o4.cw.directedisolated.semicoherent
accounting_group_user = hoitim.cheung

executable = /home/hoitim.cheung/glitch/simulate.py
output = /home/hoitim.cheung/glitch/out/simw.out
error = /home/hoitim.cheung/glitch/out/simw.err
log = /home/hoitim.cheung/glitch/out/simw.log

queue 1 
